### ISSUE TITLE
Websocket Orderbook update confusion

### ISSUE THREAD

**Issue by rangermix** [poloniex/api-docs#44]
Hi All, a quick question:

For an update for orderbook like `["o", <1 for buy 0 for sell>, "<price>", "<size>"]`, is the `"<size>"` the current size of `"<price>"` or the amount to add to/subtract from the current size?

And if the `"<size>"` is the current size can you change `<1 for buy 0 for sell>` to `<1 for ask 0 for bid>`?

**Comment by gmarchelos** [comment]
@rangermix , `size` is a new amount for that price. You don't need to do any subtractions.

**Comment by crbraun** [comment]
https://github.com/poloniex/api-docs/pull/53
