### ISSUE TITLE
returnOpenOrders command not working.

### ISSUE THREAD

**Issue by kiborg** [poloniex/api-docs#46]
command=returnOpenOrders&currencyPair=ALL&nonce=1564030153362860

doesn't return any order data. Just empty arrays : 

Array ( [BTC_ARDR] => Array ( ) [BTC_ATOM] => Array ( ) [BTC_BAT] => Array ( ) [BTC_BCHABC] => Array ( ) [BTC_BCHSV] => Array ( ) [BTC_BCN] => Array ( ) [BTC_BNT] => Array ( ) [BTC_BTS] => Array ( ) [BTC_CLAM] => Array ( ) [BTC_CVC] => Array ( ) [BTC_DASH] => Array ( ) [BTC_DCR] => Array ( ) [BTC_DGB] => Array ( ) [BTC_DOGE] => Array ( ) [BTC_EOS] => Array ( ) [BTC_ETC] => Array ( ) [BTC_ETH] => Array ( ) [BTC_FCT] => Array ( ) [BTC_FOAM] => Array ( ) [BTC_GAME] => Array ( ) [BTC_GAS] => Array ( ) [BTC_GNT] => Array ( ) [BTC_GRIN] => Array ( ) [BTC_KNC] => Array ( ) [BTC_LBC] => Array ( ) [BTC_LOOM] => Array ( ) [BTC_LPT] => Array ( ) [BTC_LSK] => Array ( ) [BTC_LTC] => Array ( ) [BTC_MAID] => Array ( ) [BTC_MANA] => Array ( ) [BTC_NAV] => Array ( ) [BTC_NMR] => Array ( ) [BTC_NXT] => Array ( ) [BTC_OMG] => Array ( ) [BTC_OMNI] => Array ( ) [BTC_PASC] => Array ( ) [BTC_POLY] => Array ( ) [BTC_QTUM] => Array ( ) [BTC_REP] => Array ( ) [BTC_SC] => Array ( ) [BTC_SNT] => Array ( ) [BTC_STEEM] => Array ( ) [BTC_STORJ] => Array ( ) [BTC_STR] => Array ( ) [BTC_STRAT] => Array ( ) [BTC_VIA] => Array ( ) [BTC_VTC] => Array ( ) [BTC_XEM] => Array ( ) [BTC_XMR] => Array ( ) [BTC_XPM] => Array ( ) [BTC_XRP] => Array ( ) [BTC_ZEC] => Array ( ) [BTC_ZRX] => Array ( ) [ETH_BAT] => Array ( ) [ETH_BNT] => Array ( ) [ETH_CVC] => Array ( ) [ETH_EOS] => Array ( ) [ETH_ETC] => Array ( ) [ETH_GAS] => Array ( ) [ETH_GNT] => Array ( ) [ETH_KNC] => Array ( ) [ETH_LOOM] => Array ( ) [ETH_LSK] => Array ( ) [ETH_MANA] => Array ( ) [ETH_OMG] => Array ( ) [ETH_QTUM] => Array ( ) [ETH_REP] => Array ( ) [ETH_SNT] => Array ( ) [ETH_STEEM] => Array ( ) [ETH_ZEC] => Array ( ) [ETH_ZRX] => Array ( ) [USDC_ATOM] => Array ( ) [USDC_BCHABC] => Array ( ) [USDC_BCHSV] => Array ( ) [USDC_BTC] => Array ( ) [USDC_DASH] => Array ( ) [USDC_DOGE] => Array ( ) [USDC_EOS] => Array ( ) [USDC_ETC] => Array ( ) [USDC_ETH] => Array ( ) [USDC_FOAM] => Array ( ) [USDC_GRIN] => Array ( ) [USDC_LTC] => Array ( ) [USDC_STR] => Array ( ) [USDC_USDT] => Array ( ) [USDC_XMR] => Array ( ) [USDC_XRP] => Array ( ) [USDC_ZEC] => Array ( ) [USDT_ATOM] => Array ( ) [USDT_BAT] => Array ( ) [USDT_BNT] => Array ( ) [USDT_BCHABC] => Array ( ) [USDT_BCHSV] => Array ( ) [USDT_BTC] => Array ( ) [USDT_DASH] => Array ( ) [USDT_DGB] => Array ( ) [USDT_DOGE] => Array ( ) [USDT_EOS] => Array ( ) [USDT_ETC] => Array ( ) [USDT_ETH] => Array ( ) [USDT_GNT] => Array ( ) [USDT_GRIN] => Array ( ) [USDT_KNC] => Array ( ) [USDT_LOOM] => Array ( ) [USDT_LSK] => Array ( ) [USDT_LTC] => Array ( ) [USDT_MANA] => Array ( ) [USDT_NXT] => Array ( ) [USDT_QTUM] => Array ( ) [USDT_REP] => Array ( ) [USDT_SC] => Array ( ) [USDT_SNT] => Array ( ) [USDT_STR] => Array ( ) [USDT_XMR] => Array ( ) [USDT_XRP] => Array ( ) [USDT_ZEC] => Array ( ) [USDT_ZRX] => Array ( ) [XMR_BCN] => Array ( ) [XMR_DASH] => Array ( ) [XMR_LTC] => Array ( ) [XMR_MAID] => Array ( ) [XMR_NXT] => Array ( ) [XMR_ZEC] => Array ( ) )

**Comment by crbraun** [comment]
Do you have any open orders?  This will only return orders that you have placed. 

My test confirmed that orders are returned for any pair for which I had open orders and that for pairs where I had no open orders the result was empty.

example:

{"BTC_ARDR":[],"BTC_ATOM":[],"BTC_BAT":[],"BTC_BCHABC":[],"BTC_BCHSV":[],"BTC_BCN":[],"BTC_BNT":[],"BTC_BTS":[],"BTC_CLAM":[],"BTC_CVC":[],"BTC_DASH":[],"BTC_DCR":[],"BTC_DGB":[],"BTC_DOGE":[],"BTC_EOS":[],"BTC_ETC":[],"BTC_ETH":[{"orderNumber":"638513368627","type":"buy","rate":"0.00176560","startingAmount":"1.00000000","amount":"1.00000000","total":"0.00176560","date":"2019-08-29 15:46:48","margin":0}],"BTC_FCT":[],"BTC_FOAM":[],"BTC_GAME":[],"BTC_GAS":[],"BTC_GNT":[],"BTC_GRIN":[],"BTC_KNC":[],"BTC_LBC":[],"BTC_LOOM":[],"BTC_LPT":[],"BTC_LSK":[],"BTC_LTC":[],"BTC_MAID":[],"BTC_MANA":[],"BTC_NAV":[],"BTC_NMR":[],"BTC_NXT":[],"BTC_OMG":[],"BTC_OMNI":[],"BTC_PASC":[],"BTC_POLY":[],"BTC_QTUM":[],"BTC_REP":[],"BTC_SC":[],"BTC_SNT":[],"BTC_STEEM":[],"BTC_STORJ":[],"BTC_STR":[],"BTC_STRAT":[],"BTC_VIA":[],"BTC_VTC":[],"BTC_XEM":[],"BTC_XMR":[],"BTC_XPM":[],"BTC_XRP":[],"BTC_ZEC":[],"BTC_ZRX":[],"ETH_BAT":[],"ETH_EOS":[],"ETH_ETC":[],"ETH_REP":[],"ETH_ZEC":[],"ETH_ZRX":[],"USDC_ATOM":[],"USDC_BCHABC":[],"USDC_BCHSV":[],"USDC_BTC":[],"USDC_DASH":[],"USDC_DOGE":[],"USDC_EOS":[],"USDC_ETC":[],"USDC_ETH":[],"USDC_GRIN":[],"USDC_LTC":[],"USDC_STR":[],"USDC_USDT":[],"USDC_XMR":[],"USDC_XRP":[],"USDC_ZEC":[],"USDT_ATOM":[],"USDT_BAT":[],"USDT_BCHABC":[],"USDT_BCHSV":[],"USDT_BTC":[],"USDT_DASH":[],"USDT_DGB":[],"USDT_DOGE":[],"USDT_EOS":[],"USDT_ETC":[],"USDT_ETH":[],"USDT_GNT":[],"USDT_GRIN":[],"USDT_LSK":[],"USDT_LTC":[],"USDT_MANA":[],"USDT_NXT":[],"USDT_QTUM":[],"USDT_REP":[],"USDT_SC":[],"USDT_STR":[],"USDT_XMR":[],"USDT_XRP":[],"USDT_ZEC":[],"USDT_ZRX":[]}
